[tool.ruff]
# Diretórios onde o Ruff deve procurar por arquivos
src = ["."]
exclude = ["migrations", ".venv", "env", "venv"]

# Versão do Python alvo
target-version = "py311"

# Seleciona os linter codes que serão aplicados
# E: pycodestyle, F: pyflakes, I: isort, UP: upgrade (ex: remoção de código obsoleto)
lint.select = ["E", "F", "I", "UP"]

# Ignora códigos específicos, se necessário (exemplo: E501 = linha muito longa)
lint.ignore = []

# Tamanho máximo de linha
line-length = 100

# Ativa a formatação automática (como o Black)
fix = true

# Define a padronização para aspas simples
[tool.ruff.format]
quote-style = "single"
